site_name: Datafast
site_description: A Python package for synthetic text dataset generation
site_author: Patrick Fleith

# Repository
repo_name: patrickfleith/datafast
repo_url: https://github.com/patrickfleith/datafast

# Theme configuration
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
