name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'datafast/**'
      - '.github/workflows/deploy-docs.yml'
    # Note: pyproject.toml changes will be ignored via the [skip docs] tag
  pull_request:
    branches: [main]
  workflow_dispatch:  # For manual triggers

# Add concurrency group to cancel in-progress jobs
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # Skip if commit message contains [skip docs]
    if: "!contains(github.event.head_commit.message, '[skip docs]')"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - run: pip install mkdocs-material mkdocstrings[python] mkdocs-material-extensions
      - run: pip install -e .
      - run: mkdocs build
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      
      - uses: actions/deploy-pages@v4
        id: deployment
